### ISSUE TITLE
说下轨迹打点

### ISSUE THREAD

**Issue by bg4vrg** [bg4uvr/4G-Tracker#1]
非常感谢bg4uvr的努力，使我们用上了物美价廉的aprs tracker！

上周抄作业做了2套，今天同城小伙伴问我为什么打点有点稀，而且不是所有路口都能准确打点。
我分析了下他的轨迹并和其他国内另外1家成品的轨迹图做了对比，发现确实没有人家密，直观表现在使用aprs.tv观察“轨迹切换”动图时呼号汽车图标在轨迹图上跳动比较大，比较直观的说像看电影打游戏一样卡帧了。
我到aprs.fi上分析了2种设备的数据包速率。使用国内某家成品设备的包速率约17秒就向aprs is服务器发送一个数据包，而本程序评价94秒像服务器发送一个数据包（这还是我手动降低了包发送间隔，并把智能打点的角度调低；如果是默认设置可能间隔周期更长）。
那么原因就很明了了，打点稀松竟可能是因为遵守了aprs规则，本来aprs设计出来就不是用来做做密集上报数据的。毕竟aprs.fi网站也加粗提示“这个太粘正在以很高的速率发送数据包，这可能导致aprs网络的壅塞”

**Comment by bg4vrg** [comment]
无需回答

**Comment by bg4uvr** [comment]
发点稀疏确实是有意设计的，希望能够用尽量少的点来尽量匹配实际路线，确实无法做到所有转弯处都能准时发点。不过今天稍早前还是发现发点算法的一处不足，经过修正改进后，我自己已经在测试0.0.15版了。经过这次改进后，在同样的配置参数情况下，发点数量应该会有所增加。如果经过测试感觉良好没有其他不良反应，我会发布一次远程更新，届时欢迎反馈使用感受。

**Comment by bg4uvr** [comment]
尤其是“最小变化方位角”设置值较小时，发点数量增加可能会更明显。
